# Generated by Django 3.1.5 on 2021-01-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210106_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image_title',
            new_name='title',
        ),
    ]
